In [34]:
values = [1, 2, 3, 4, 5]
multiply = 3

new_values = []
for i in values:
    new_values.append(i*multiply)

new_values


[3, 6, 9, 12, 15]

In [35]:
values = [1, 2, 3, 4, 5]
multiply = 3

new_values = [i*multiply for i in values]
new_values

[3, 6, 9, 12, 15]

In [40]:
import numpy as np
values_array = np.array([1, 2, 3, 4, 5])
multiply = 3
values_array * multiply
values_array ** 2 * 3.14159

array([ 3.14159, 12.56636, 28.27431, 50.26544, 78.53975])

In [37]:
import numpy as np
values_array = np.array([1,2,3,4,5])
multiply = 3
values_array * multiply


array([ 3,  6,  9, 12, 15])

In [38]:
import numpy as np 
np.random.randint(50,100,size=(50,5))

array([[65, 55, 71, 63, 55],
       [80, 84, 88, 53, 52],
       [69, 88, 79, 67, 99],
       [65, 67, 52, 75, 57],
       [80, 88, 51, 57, 99],
       [78, 52, 73, 59, 88],
       [95, 74, 92, 77, 50],
       [66, 67, 75, 72, 71],
       [82, 86, 86, 51, 59],
       [86, 91, 56, 87, 80],
       [60, 52, 97, 63, 61],
       [90, 87, 79, 89, 80],
       [50, 83, 86, 86, 83],
       [56, 99, 68, 80, 83],
       [71, 95, 94, 50, 74],
       [92, 94, 92, 87, 96],
       [56, 68, 91, 82, 73],
       [87, 82, 70, 75, 93],
       [64, 50, 57, 66, 69],
       [79, 84, 77, 87, 73],
       [96, 89, 55, 95, 75],
       [83, 83, 61, 85, 61],
       [74, 78, 58, 92, 60],
       [82, 51, 52, 55, 99],
       [57, 61, 82, 74, 70],
       [60, 67, 63, 98, 52],
       [56, 83, 58, 98, 87],
       [88, 98, 72, 77, 52],
       [59, 55, 99, 51, 57],
       [97, 85, 55, 98, 77],
       [94, 72, 99, 66, 86],
       [64, 61, 89, 98, 97],
       [50, 92, 74, 60, 65],
       [56, 52, 73, 50, 70],
       [83, 72