In [ ]:
5, 7

In [ ]:
(5,7)

In [2]:
(5,)


(5,)

In [8]:
list_a = [1,3,5,7,9]
list_b = [2,4,6,8,10]
list_a+list_b

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

In [9]:
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [14]:
import numpy as np
l=[[1,2,3],[4,5,6]]
array = np.array(l)
array.ndim,array.shape,array.size,array.dtype

(2, (2, 3), 6)

In [ ]:
import numpy as np
array = np.array(l)

In [15]:
import numpy as np
np.random.randn(10,5)

array([[ 0.17241975, -0.43673543, -1.43944742, -2.99107207,  0.67020899],
       [ 0.28937337, -0.09383265, -1.05899099, -0.13915928,  0.18368657],
       [-0.57823698,  0.98492549,  0.6264112 , -0.13728984,  0.57571186],
       [ 0.85788015, -0.61570903, -2.38453421,  0.17280922, -0.16332915],
       [-0.70490683,  1.69681931,  3.20473052, -0.02421812, -1.02930552],
       [ 0.48354713, -0.60241956, -0.09111449,  0.48092845,  0.50524049],
       [-0.54150824, -0.07160479,  0.51960615, -0.54413826, -1.41942299],
       [ 1.14237551, -0.04223566,  1.43376438,  0.13430374, -0.70547709],
       [ 0.05051514,  0.12723485,  2.54915818,  0.06706434,  0.59054574],
       [-1.80602302,  0.98190128, -0.08158276,  1.06192721, -0.64255882]])

In [48]:
#50個學生,每個學生有5個分數(50-100)
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 72,  85,  79,  94,  66],
       [ 86,  95,  96,  66,  93],
       [ 63,  73,  51,  57,  67],
       [ 89,  96,  82,  92,  68],
       [ 94,  76,  70,  74,  75],
       [ 91,  94, 100,  73,  63],
       [ 84,  92,  96,  88,  84],
       [ 76,  97,  94,  72,  70],
       [100,  82,  88,  62,  81],
       [ 56,  85,  68,  78,  77],
       [ 51,  75,  83,  76,  50],
       [ 59,  76,  61,  92,  72],
       [ 67,  76,  54,  72,  58],
       [ 96,  90,  56,  76,  57],
       [ 72,  96,  76,  66,  75],
       [ 93,  91,  98,  78,  57],
       [ 91,  73,  67,  84,  82],
       [ 90,  88,  60,  86,  64],
       [ 57,  89,  91,  71,  76],
       [ 51,  57,  84,  73,  68],
       [ 69,  86,  92,  75,  63],
       [ 98,  58,  68,  58,  59],
       [ 94,  72,  67,  87,  63],
       [ 63,  89,  92,  61,  74],
       [ 82,  85,  80,  74,  51],
       [ 88,  56,  87,  93,  77],
       [ 50,  95,  74,  76,  53],
       [ 53,  74,  95,  92,  88],
       [ 65,  54,  83,  55,  98],
       [ 88,  

In [44]:
# 第一個學生
scores[0,:]
# 前五個學生
scores[:5,:]
# 最後五個學生
scores[-5:,:]

array([[ 85,  60,  73,  69,  66],
       [ 98,  90,  83,  73,  90],
       [ 94, 100,  85,  96,  89],
       [ 56,  68,  79,  67,  78],
       [ 97,  53,  79,  50,  71]])

In [ ]:
scores[:,0]

In [ ]:
scores[:,1]

In [41]:
total=scores[:,0]+scores[:,1]+scores[:,2]+scores[:,3]+scores[:,4]
total

array([448, 378, 408, 306, 359, 336, 406, 365, 393, 377, 357, 352, 406,
       416, 430, 394, 317, 352, 402, 340, 425, 452, 383, 386, 371, 411,
       359, 364, 317, 340, 390, 355, 385, 338, 389, 346, 357, 310, 395,
       340, 409, 381, 367, 352, 369, 353, 434, 464, 348, 350])

In [49]:
# 使用統計的方法
np.sum(scores,axis=1)

np.int64(18683)

In [51]:
# 每個學生平均
np.mean(scores,axis=1)

array([79.2, 87.2, 62.2, 85.4, 77.8, 84.2, 88.8, 81.8, 82.6, 72.8, 67. ,
       72. , 65.4, 75. , 77. , 83.4, 79.4, 77.6, 76.8, 66.6, 77. , 68.2,
       76.6, 75.8, 74.4, 80.2, 69.6, 80.4, 71. , 79. , 72.2, 82.8, 64.4,
       61. , 80.8, 61.8, 75. , 75.6, 78.8, 82.8, 71.2, 78. , 58.4, 64.6,
       72.4, 80.4, 67.2, 79. , 64. , 71.8])